### ISSUE TITLE
[aws-load-balancer-controller] Unable to deploy stack 

### ISSUE THREAD

**Issue by briancaffey** [briancaffey/django-cdk#26]
Errors deploying the stack, seems to be related to AWS Load Balancer Controller

```
Received response status [FAILED] from custom resource. Message returned: Error: Operation failed after 3 attempts: b'Unable to connect to the server: dial tcp: lookup C4764B11B1ACD0375678D408758A6E73.sk1.us-east-1.eks.amazonaws.com on 169.254.78.1:53: read udp 169.254.76.1:48370->169.254.78.1:53: i/o timeout\n' Logs: /aws/lambda/DjangoEksStack-awscdkawseksKubectl-Handler886CB40B-NgbKmkuyQRzI at invokeUserFunction (/var/task/framework.js:95:19) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async onEvent (/var/task/framework.js:19:27) at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: 42c5be50-d5cd-4a7d-8a6e-832bc0899d8e)
```

This could be related to https://github.com/aws/aws-cdk/issues/4087

**Comment by briancaffey** [comment]
This was fixed by adding `A.node.dependsOn(B)`.
